---
- name: test
  hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  tasks:
    - name: foo
      shell: echo bar
      register: foo

    - name: test variable
      lineinfile:
          path: /home/lbermejo/test.txt
          regexp: '^export JAVA_HOME="/usr/lib/jvm/foo"'
          state: present
          line: 'export JAVA_HOME="/usr/lib/jvm/{{ foo.stdout }}"'
          backup: true

    - name: Find and delete old jdk/jre binaries
      find:
        paths: /home/lbermejo/java
        patterns: 'jre1.8*,jdk1.8*'
        file_type: directory
      register: found_dirs
    - name: Delete found directories
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ found_dirs.files }}"
 